### ISSUE TITLE
(last ?) model syntax update

### ISSUE THREAD

**Issue by albop** [EconForge/Dolo.jl#36]
This echoes an old discussion from this summer. The idea would be to make the `options` field truly optional, by moving its current fields out of it.

A model file would have two new optional sections like in the following example
```
domain:
    k: [k*0.5, k*1.1]
exogenous: !Normal
    sigma: [[0.0]]
```
Exogenous section would be the same as today, but outside of `options:`.  The  `domain:` section would list pairs of upper-bound/lower-bound variables, for each state variable. States that are not in the model would be ignored (this is useful when playing with multiple model.

`options:` section would still contain information about a grid and an interpolation method, like:
```
options:
            grid: !Cartesian
                orders: [100,100]
            interpolation: splines
```

What made me change my mind was the realization that when the user specify model, we should be able to propose sensible options for 90% of the cases.
